spring:
  application:
    name: ecommerce

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: ecommerce
        hbm2ddl:
          create_namespaces: true


  security:
    jwt:
      secret-key: KmOh41wlv912wgrGcwk6o4zsDm6lAD6VqBtBlcDvYE5
      expiration: 900000
      refresh-token:
        expiration: 604800000

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
      disable-swagger-default-url: true